# RISC-V (RV32IM) assembly
# Generated by compiler project — RISC-V backend
# Source IR: output.ir

	.data
	.align	2

x:	.word	0

	# --- temporaries ---
t_1:	.word	0
t_2:	.word	0
t_3:	.word	0
t_4:	.word	0

	.text
	.globl	main
	.type	main, @function
main:
	# ---- program entry ----

	# IR_BEGIN
	# decl int x
	# t1 = addr x
	la	t0, x
	sw	t0, t_1, t6
	# t2 = const int 1
	li	t0, 1
	sw	t0, t_2, t6
	# store [t1], t2
	lw	t1, t_1
	lw	t0, t_2
	sw	t0, 0(t1)
	# t3 = t2
	lw	t0, t_2
	sw	t0, t_3, t6
	# print t2
	lw	a0, t_2
	li	a7, 1
	ecall
	li	a0, 10
	li	a7, 11
	ecall
	# t4 = const int 0
	li	t0, 0
	sw	t0, t_4, t6
	# ret t4
	lw	a0, t_4
	j	.Lexit
	# IR_END

	# ---- program exit ----
.Lexit:
	li	a7, 10
	ecall
	.size	main, .-main
